FROM node:22-slim

WORKDIR /app

COPY package.json package-lock.json .npmrc ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_TOKEN_ADDRESS
ENV NEXT_PUBLIC_TOKEN_ADDRESS=$NEXT_PUBLIC_TOKEN_ADDRESS

ARG NEXT_PUBLIC_HELIUS_API_KEY
ENV NEXT_PUBLIC_HELIUS_API_KEY=$NEXT_PUBLIC_HELIUS_API_KEY

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
